# Generated by Django 3.2.7 on 2021-12-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_menu',
            field=models.BooleanField(default=False, verbose_name='是否可以做菜单'),
        ),
    ]
