# Generated by Django 3.2.7 on 2021-12-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_permission_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='URL别名'),
        ),
    ]
